[package]
name = "aster"
version = "0.26.1"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A libsyntax ast builder"
repository = "https://github.com/serde-rs/aster"
include = ["Cargo.toml", "src/**/*.rs"]

[features]
with-syntex = ["syntex_syntax"]
unstable-testing = ["clippy", "compiletest_rs"]

[dependencies]
syntex_syntax = { version = "^0.43.0", optional = true, git = "https://github.com/jchlapinski/syntex.git" } 
clippy = { version = "0.*", optional = true }
compiletest_rs = { version = "^0.2.0", optional = true }

[[test]]
name = "test"
path = "tests/test.rs"
